version: 2.1

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Data Analytics Portfolio]
description: [Jessica Tanumihardja's data analytics projects]

  #theme source: https://pages.github.com/themes/ 

#theme: jekyll-theme-minimal

#minimal:
#  social_links:
#    - { platform: github,  user_url: "https://github.com/jtanumihardja" }
#    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jessica-tanumihardja/" }

# Use this code base if we want to use it for something else:
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
